ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS backup_type character varying(20);
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS destination character varying(20);
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS file_size_bytes bigint;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS file_path text;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS checksum character varying(128);
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS encryption_key_id character varying(100);
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.backup_log ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS pattern_type character varying(100);
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS pattern_data jsonb;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS confidence real;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS observation_count integer;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS first_seen timestamp with time zone;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS last_seen timestamp with time zone;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.behavioral_patterns ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS meeting text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS text text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS owner_rascal text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_action_items ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS agent_id text;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS agent_name text;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS finished_at timestamp with time zone;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS tokens_in integer;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS tokens_out integer;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS cost_usd numeric(12,6);
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS duration_ms integer;
ALTER TABLE public.boss_agent_runs ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS actor text;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS action text;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS target text;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS detail text;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS ok boolean;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS latency_ms integer;
ALTER TABLE public.boss_audit ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS period text;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS planned_cents bigint;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS actual_cents bigint;
ALTER TABLE public.boss_budget ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS session_id uuid;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS tokens_in integer;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS tokens_out integer;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_chat_messages ADD COLUMN IF NOT EXISTS tool_trace text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS rascal_handle text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS system_prompt text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS cc_session_id text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS agent_kind text;
ALTER TABLE public.boss_chat_sessions ADD COLUMN IF NOT EXISTS workspace_dir text;
ALTER TABLE public.boss_conversations ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_conversations ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.boss_conversations ADD COLUMN IF NOT EXISTS messages jsonb;
ALTER TABLE public.boss_conversations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS tags jsonb;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS date_added timestamp with time zone;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS raw jsonb;
ALTER TABLE public.boss_crm_contacts ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS pipeline_id text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS stage_id text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS stage_name text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS contact_id text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS monetary_value numeric;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS date_added timestamp with time zone;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS raw jsonb;
ALTER TABLE public.boss_crm_opportunities ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.boss_crm_snapshot ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_crm_snapshot ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_crm_snapshot ADD COLUMN IF NOT EXISTS snapshot jsonb;
ALTER TABLE public.boss_crm_snapshot ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS account text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS to_addr text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS reply_subject text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS rating integer;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS rating_note text;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_email_drafts ADD COLUMN IF NOT EXISTS rated_at timestamp with time zone;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS message_id text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS account_email text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS sender text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS received_at timestamp with time zone;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS needs_attention boolean;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS action_taken text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS draft_content text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS golden_nugget text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS invoice_amount numeric;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS invoice_due_date date;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS boss_notes text;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS processed_at timestamp with time zone;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone;
ALTER TABLE public.boss_email_log ADD COLUMN IF NOT EXISTS resolved_by text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS vendor text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS amount_cents bigint;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS currency text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS paid_date date;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS source_ref text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.boss_expenses ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS question text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS answer text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS client text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS source_email_id text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_faq ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS mid text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS direction text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS sender_id text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS sender_name text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.boss_fb_messages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS participant_id text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS participant_name text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS last_message_at timestamp with time zone;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS last_message_preview text;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS last_message_from_page boolean;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS unread_count integer;
ALTER TABLE public.boss_fb_threads ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_finance_snapshot ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_finance_snapshot ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_finance_snapshot ADD COLUMN IF NOT EXISTS snapshot jsonb;
ALTER TABLE public.boss_finance_snapshot ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS api text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS auth_type text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS credential text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS project_id text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS cost_model text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.boss_google_registry ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS api text;
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS units integer;
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS est_cost_usd numeric(12,6);
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_google_usage ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS kind text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS severity text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS detail text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS observed numeric;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS baseline numeric;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS playbook_id uuid;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS timeline jsonb;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS opened_at timestamp with time zone;
ALTER TABLE public.boss_incidents ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS k text;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS detail jsonb;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS source_manager text;
ALTER TABLE public.boss_knowledge ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS text text;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS link text;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS post_id text;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS author text;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS posted_at timestamp with time zone;
ALTER TABLE public.boss_linkedin_posts ADD COLUMN IF NOT EXISTS media_kind text;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS confidence real;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS access_count integer;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS last_accessed timestamp with time zone;
ALTER TABLE public.boss_memory ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS app_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS app_secret_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS webhook_verify_token text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS system_user_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_page_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_page_name text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_page_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS ig_business_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS ig_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS threads_user_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS threads_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_waba_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_phone_number_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_display_phone text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS ads_account_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS ads_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS connected_at timestamp with time zone;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_messaging_app_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_messaging_app_secret_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS fb_messaging_token_enc text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_app_id text;
ALTER TABLE public.boss_meta_credentials ADD COLUMN IF NOT EXISTS wa_app_secret_enc text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS object text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS external_id text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS payload jsonb;
ALTER TABLE public.boss_meta_events ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_oauth_state ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE public.boss_oauth_state ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE public.boss_oauth_state ADD COLUMN IF NOT EXISTS services text[];
ALTER TABLE public.boss_oauth_state ADD COLUMN IF NOT EXISTS code_verifier text;
ALTER TABLE public.boss_oauth_state ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS account_id text;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS access_token text;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS refresh_token text;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS scopes text[];
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_oauth_tokens ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS step text;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS completed_steps jsonb;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS skipped_steps jsonb;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS connector_progress jsonb;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS agent_progress jsonb;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS data jsonb;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
ALTER TABLE public.boss_onboarding ADD COLUMN IF NOT EXISTS last_activity_at timestamp with time zone;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS handle text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS cli text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS client text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS project_dir text;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_outsiders ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS instructions text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS cron_expression text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS tools text[];
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS last_run_at timestamp with time zone;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS last_result text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS run_count integer;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS error_count integer;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_persistent_agents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS stages jsonb;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_pipelines ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS kind text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS match_key text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS symptom text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS diagnosis text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS resolution text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS severity text;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS times_used integer;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_playbooks ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS handle text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS cli text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS client text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS project_dir text;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_rascals ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS overall_rating numeric(3,2);
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS total_reviews integer;
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS sources jsonb;
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.boss_reviews_snapshot ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS persona_doc text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS current_model text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS trust_level text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS reflections jsonb;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS active_goals jsonb;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_self_state ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS tools_used text[];
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS decisions text[];
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS learnings text[];
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS message_count integer;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS model_used text;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS ended_at timestamp with time zone;
ALTER TABLE public.boss_sessions ADD COLUMN IF NOT EXISTS duration_ms integer;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS channel_id text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS channel_name text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS ts text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS user_name text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS text text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS thread_ts text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS is_sale boolean;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS sale_amount numeric;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS permalink text;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS posted_at timestamp with time zone;
ALTER TABLE public.boss_slack_messages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS task_id uuid;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS stage text;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS agent text;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS output text;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS output_files text[];
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.boss_stage_log ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_task_frequency ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE public.boss_task_frequency ADD COLUMN IF NOT EXISTS count integer;
ALTER TABLE public.boss_task_frequency ADD COLUMN IF NOT EXISTS last_seen timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS pipeline_id uuid;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS current_stage text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS assigned_agent text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS assigned_client text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS stage_history jsonb;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS view_column text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS due_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS archived_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS bucket text;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS gate_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS picked_at timestamp with time zone;
ALTER TABLE public.boss_tasks ADD COLUMN IF NOT EXISTS kind text;
ALTER TABLE public.boss_telegram_pairs ADD COLUMN IF NOT EXISTS chat_id bigint;
ALTER TABLE public.boss_telegram_pairs ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.boss_telegram_pairs ADD COLUMN IF NOT EXISTS username text;
ALTER TABLE public.boss_telegram_pairs ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE public.boss_telegram_pairs ADD COLUMN IF NOT EXISTS paired_at timestamp with time zone;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS business_name text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS primary_email text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS openrouter_api_key text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS plan text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS onboarding_completed boolean;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS onboarding_step text;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_tenants ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS active boolean;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS last_login_at timestamp with time zone;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS preferences jsonb;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_users ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS service text;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS secret text;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.boss_vault ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS conversation_id text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS user_speech text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS vasari_response text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS current_page text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS tools_used text[];
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS model_used text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS corrected_speech text;
ALTER TABLE public.boss_voice_transcripts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS contact_id text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS push_name text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS verified_name text;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS is_my_contact boolean;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS is_blocked boolean;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS is_group boolean;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS source_payload jsonb;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS last_seen_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_contacts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS chat_id text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS authored_by text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS reply_to_wa_message_id text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS reasoning text;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_drafts ADD COLUMN IF NOT EXISTS sent_wa_message_id text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS chat_id text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS wa_message_id text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS direction text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS from_me boolean;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS author text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS message_type text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS media_url text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS reply_to_wa_message_id text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS ack_status text;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS ingested_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_messages ADD COLUMN IF NOT EXISTS sender_name text;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS chat_id text;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS agent_handle text;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS confidence_threshold real;
ALTER TABLE public.boss_whatsapp_monitors ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS chat_id text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS send_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS draft_approved boolean;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS wa_message_id text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_scheduled ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS chat_id text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS is_group boolean;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS last_message_wa_id text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS last_message_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS last_message_preview text;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS last_message_from_me boolean;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS unread_count integer;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.boss_whatsapp_threads ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS brain_type character varying(50);
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS label character varying(100);
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS endpoint text;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS model character varying(100);
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS api_key_encrypted bytea;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS capabilities_json jsonb;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS is_primary boolean;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS is_fallback boolean;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.brain_config ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS contact_id text;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.cached_contacts ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS message_id text;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS from_address text;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS to_addresses text[];
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS snippet text;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS date timestamp with time zone;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS is_read boolean;
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS labels text[];
ALTER TABLE public.cached_emails ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS event_id text;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS start timestamp with time zone;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS "end" timestamp with time zone;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS attendees text[];
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE public.cached_events ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS file_id text;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS mime_type text;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS path text;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS size bigint;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS modified timestamp with time zone;
ALTER TABLE public.cached_files ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS task_id text;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS due timestamp with time zone;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS list text;
ALTER TABLE public.cached_tasks ADD COLUMN IF NOT EXISTS synced_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS provider character varying(50);
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS file_id character varying(500);
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS file_name text;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS file_path text;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS file_size_bytes bigint;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS last_modified_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS last_accessed_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS proposal_type character varying(20);
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS confidence real;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS destination text;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS executed_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS batch_id uuid;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.cleanup_proposals ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS provider character varying(50);
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS account_email character varying(320);
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS account_name character varying(255);
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS account_label character varying(100);
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS services_json jsonb;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS is_primary boolean;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS connected_at timestamp with time zone;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS disconnected_at timestamp with time zone;
ALTER TABLE public.connected_accounts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS event_type character varying(100);
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS conditions jsonb;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS actions jsonb;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS run_count integer;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS last_triggered timestamp with time zone;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.event_rules ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS event_type character varying(100);
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS source character varying(50);
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS payload jsonb;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS correlation_id uuid;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS processed boolean;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS processed_at timestamp with time zone;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS error text;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS provider character varying(50);
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS rule_type character varying(50);
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS match_pattern jsonb;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS action_params jsonb;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS run_count integer;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS last_triggered timestamp with time zone;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.file_rules ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS service character varying(100);
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS response_time_ms integer;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS error text;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.health_checks ADD COLUMN IF NOT EXISTS checked_at timestamp with time zone;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS service character varying(100);
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS severity character varying(20);
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS error_context jsonb;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS diagnosis text;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS fix_attempted text;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS fix_result text;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS attempts jsonb;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS playbook_id uuid;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS escalated boolean;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS escalation_sent_at timestamp with time zone;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS escalation_channel character varying(50);
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS resolved_by character varying(50);
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS invited_by text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.invites ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS profile_json jsonb;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS communication_style character varying(100);
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS onboarding_complete boolean;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS profile_version integer;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS last_synthesized_at timestamp with time zone;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.learning_profiles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS sender text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS headline text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS raw_snippet text;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS used_at timestamp without time zone;
ALTER TABLE public.newsroom_tips ADD COLUMN IF NOT EXISTS used_in_episode text;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS provider character varying(50);
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS account_label character varying(100);
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS service character varying(100);
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS access_token_encrypted bytea;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS refresh_token_encrypted bytea;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS scopes text[];
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS last_refresh_at timestamp with time zone;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS refresh_error text;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.oauth_tokens ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS platform character varying(50);
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS items_processed integer;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS total_items integer;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS started_at timestamp with time zone;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
ALTER TABLE public.onboarding_progress ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS handle text;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS poll_seconds integer;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS last_run_at timestamp with time zone;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS last_result text;
ALTER TABLE public.platform_manager ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS failure_signature text;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS service character varying(100);
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS severity character varying(20);
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS diagnosis_steps jsonb;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS fix_steps jsonb;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS verification text;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS success_count integer;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS failure_count integer;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS last_used timestamp with time zone;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS created_from_incident uuid;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS rule text;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS category character varying(100);
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS weight real;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS source character varying(50);
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.preferences ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.runtime_config ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE public.runtime_config ADD COLUMN IF NOT EXISTS value text;
ALTER TABLE public.runtime_config ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.runtime_config ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.schema_migrations ADD COLUMN IF NOT EXISTS filename text;
ALTER TABLE public.schema_migrations ADD COLUMN IF NOT EXISTS applied_at timestamp with time zone;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS token text;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS device_hint character varying(255);
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS ip_address inet;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.slack_agent_grants ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.slack_agent_grants ADD COLUMN IF NOT EXISTS agent_handle text;
ALTER TABLE public.slack_agent_grants ADD COLUMN IF NOT EXISTS scopes jsonb;
ALTER TABLE public.slack_agent_grants ADD COLUMN IF NOT EXISTS granted_at timestamp with time zone;
ALTER TABLE public.slack_agent_grants ADD COLUMN IF NOT EXISTS granted_by text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS flagged_by text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS source_channel text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS source_ts text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS source_user text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS source_user_name text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS preview text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS permalink text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS acknowledged_at timestamp with time zone;
ALTER TABLE public.slack_attention ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS account_id uuid;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS service text;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS last_sync timestamp with time zone;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS next_sync timestamp with time zone;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS error text;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.sync_state ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS slug character varying(63);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS brain_type character varying(50);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS brain_config jsonb;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS suite_type character varying(20);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS plan character varying(50);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS timezone character varying(100);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS agent_kind text;
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS agent_handle text;
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS daily_usd_cap numeric(10,2);
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS hard_stop boolean;
ALTER TABLE public.token_budget ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS tenant_id text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS ts timestamp with time zone;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS agent_kind text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS agent_handle text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS session_id uuid;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS task_class text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS tokens_in integer;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS tokens_out integer;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS cached_in integer;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS cost_usd numeric(12,6);
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS latency_ms integer;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS escalated boolean;
ALTER TABLE public.token_ledger ADD COLUMN IF NOT EXISTS meta jsonb;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS username character varying(100);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email character varying(320);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role character varying(50);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS display_name character varying(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS settings jsonb;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_active_at timestamp with time zone;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS totp_secret text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS totp_enabled boolean;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS passkey_hash character varying(64);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS onboarding_wizard_complete boolean;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS device_id character varying(100);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS room character varying(100);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS device_type character varying(50);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS wake_word character varying(100);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS stt_provider character varying(50);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS tts_provider character varying(50);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS last_seen_at timestamp with time zone;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS firmware_version character varying(50);
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS ip_address inet;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS config jsonb;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.voice_devices ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
