/**
 * Core types for the Confidence Threshold Engine.
 *
 * Every proposed action gets an ActionProposal. The engine evaluates it and
 * returns an ActionDecision with a tier, score, and full reasoning chain.
 */

import type { UserProfile } from '@boss/core';
import type { LearningProfile, Preference } from '@boss/learning';

// ── Tiers ───────────────────────────────────────────────────────────────────

/**
 * The three autonomy tiers that determine how BOS handles a proposed action.
 *
 * - autonomous  — Execute immediately and log. No human needed.
 * - propose     — Generate a draft and queue for human approval.
 * - escalate    — Pause and surface directly to the user. Too complex or risky
 *                 to proceed without explicit guidance.
 */
export type ConfidenceTier = 'autonomous' | 'propose' | 'escalate';

// ── Action Proposal ─────────────────────────────────────────────────────────

/**
 * The domain of the proposed action — used to select relevant scoring factors.
 */
export type ActionDomain =
  | 'communication'   // Email, message, reply
  | 'scheduling'      // Calendar events, meeting requests
  | 'tasks'           // Task creation, assignment, completion
  | 'files'           // File ops — upload, move, rename, delete
  | 'contacts'        // Contact creation or update
  | 'general';        // Anything that doesn't fit a specific domain

/**
 * A proposed action surfaced by the brain router before execution.
 * This is the input to the confidence engine.
 */
export interface ActionProposal {
  /** Unique ID for this proposal. Generated by caller. */
  id: string;

  /** Which functional domain this action belongs to. */
  domain: ActionDomain;

  /**
   * Human-readable intent summary for reasoning output.
   * Example: "Reply to John Smith acknowledging receipt of invoice"
   */
  intent: string;

  /**
   * The actual action payload the connector layer would execute.
   * Opaque to the confidence engine — carried through and attached to decision.
   */
  payload: Record<string, unknown>;

  /**
   * Entities involved — contacts, files, calendar events.
   * Used for entity priority scoring.
   */
  entities: ActionEntity[];

  /**
   * State snapshot at proposal time — current calendar, open tasks, etc.
   * Used for context friction scoring.
   */
  currentState?: CurrentState;

  /** ISO timestamp when this proposal was generated. */
  proposedAt: string;
}

/**
 * An entity referenced in the action — a contact, calendar event, file, etc.
 */
export interface ActionEntity {
  type: 'contact' | 'calendar_event' | 'file' | 'task' | 'other';
  id: string;
  label: string;
  /** Whether this entity is already known to BOS. */
  isKnown: boolean;
}

/**
 * A snapshot of relevant state at proposal time.
 * Passed in by the caller — BOS's connector layer assembles this.
 */
export interface CurrentState {
  /** Upcoming calendar events in the next 24 hours. */
  upcomingEvents?: CalendarEventSummary[];
  /** Open high-priority tasks. */
  openPriorityTasks?: TaskSummary[];
  /** Any flags from recent interactions. */
  contextFlags?: string[];
}

export interface CalendarEventSummary {
  id: string;
  title: string;
  startTime: string;
  endTime: string;
  attendees: string[];
  priority: 'low' | 'medium' | 'high';
}

export interface TaskSummary {
  id: string;
  title: string;
  dueDate?: string;
  priority: 'low' | 'medium' | 'high';
}

// ── User Context ────────────────────────────────────────────────────────────

/**
 * Everything the confidence engine needs to know about the user.
 * Assembled from @boss/learning and passed in by the brain middleware.
 */
export interface UserContext {
  user: UserProfile;
  learningProfile: LearningProfile;
  preferences: Preference[];
  /** Action history relevant to the current domain. */
  recentActions?: HistoricalAction[];
  /** Alpha mode flag. When true, autonomous tier is blocked. */
  alphaMode: boolean;
}

/**
 * A previously executed action stored in history for precedent matching.
 */
export interface HistoricalAction {
  id: string;
  domain: ActionDomain;
  intent: string;
  /** The tier it was assigned at the time. */
  assignedTier: ConfidenceTier;
  /** Whether the user approved, rejected, or modified it. */
  outcome: 'approved' | 'rejected' | 'modified' | 'auto_executed';
  executedAt: string;
  /** Compact representation for similarity matching. */
  signature: string;
}

// ── Scoring ─────────────────────────────────────────────────────────────────

/**
 * The interface all scoring factor modules implement.
 * Each factor evaluates one dimension of confidence and returns 0.0–1.0.
 */
export interface ScoringFactor {
  /** Identifier for this factor. Used in reasoning output. */
  readonly name: string;

  /**
   * Weight applied to this factor's score when computing the composite.
   * All factor weights are normalized by the engine — they don't need to sum to 1.
   */
  readonly weight: number;

  /**
   * Evaluate this factor and return a normalized score.
   *
   * @returns 0.0 (lowest confidence) to 1.0 (highest confidence)
   */
  score(proposal: ActionProposal, context: UserContext): Promise<FactorResult>;
}

/**
 * The output of a single scoring factor.
 */
export interface FactorResult {
  /** Factor identifier — must match ScoringFactor.name. */
  factor: string;
  /** Normalized score 0.0–1.0. */
  score: number;
  /** Weight used in composite calculation. */
  weight: number;
  /** One-line explanation for the reasoning chain. */
  rationale: string;
  /** Optional signals that drove the score — shown in verbose output. */
  signals?: string[];
}

// ── Decision ────────────────────────────────────────────────────────────────

/**
 * The output of the confidence engine for a single action proposal.
 * This is what the brain router or action dispatcher receives.
 */
export interface ActionDecision {
  /** Echo of the original proposal ID. */
  proposalId: string;

  /** The assigned autonomy tier. */
  tier: ConfidenceTier;

  /**
   * Composite confidence score — weighted average of all factor scores.
   * 0.0 = minimum confidence, 1.0 = maximum confidence.
   */
  score: number;

  /**
   * Per-factor breakdown. Full audit trail of how the score was reached.
   */
  factors: FactorResult[];

  /**
   * Human-readable explanation of the decision.
   * Used in proposal/escalation notifications to the user.
   */
  reasoning: string;

  /**
   * If alpha mode overrode the tier, this records what the raw tier would
   * have been before the override was applied.
   */
  alphaModeOverride?: {
    rawTier: ConfidenceTier;
    rawScore: number;
    reason: string;
  };

  /** ISO timestamp of when this decision was made. */
  decidedAt: string;
}
